global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'monitoring'

rule_files:
  - "alert.rules"


scrape_configs:

  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']
      - targets: 
        - node-exporter:9100
#        labels:
#          name: node-exporter
      - targets:
        - cadvisor:8080
#        labels:
#          name: cAdvisor



  - job_name: 'prometheus-client'

    static_configs:
      - targets:
        - 35.228.15.181:9100
        labels:
          name: client-node-exporter
      - targets:
        - 35.228.15.181:8080
        labels:
          name: client-cAdvisor


alerting:
  alertmanagers:
    - static_configs:
      - targets: 
        - alertmanager:9093
