

version: '3.3'

networks:
  prometheus:

services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-server/:/prometheus/
      - ./prometheus:/etc/prometheus/
    networks:
      - prometheus
#    restart: always
#
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=lalk
      - GF_SECURITY_ADMIN_USER=admin
    networks:
      - prometheus 
#    restart: always
#
  nginx:
    image: nginx
    volumes:
      - ./nginx_no_ssl.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks:
      - prometheus
    depends_on:
      - prometheus
#    restart: always
#
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    networks:
      - prometheus
#    restart: always
#
  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - prometheus
#    restart: always
#
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - prometheus
#    restart: always
